### ISSUE TITLE
Let's setup a wiki, which will help us document the project better

### ISSUE THREAD

**Issue by TensorMonkey** [TensorMonkey/browsehandsfree#11]
GitHubs existing wiki system is convenient, but it'll be more helpful to have a project on https://wiki.browsehandsfree.com 

- [x] Provision space on Google Cloud for MediaWiki
- [x] Setup DNS from CloudNS
- [x] Setup branding
- [x] Setup SSL
- [x] Redirect http to https
- [x] Setup home page

**Comment by TensorMonkey** [comment]
Complete! https://wiki.browsehandsfree.com
![image](https://user-images.githubusercontent.com/43509032/46310846-56a06d80-c575-11e8-8232-5898ae79b0ba.png)
