### ISSUE TITLE
As a user, I want a proxy that'll let me visit different URLs

### ISSUE THREAD

**Issue by TensorMonkey** [TensorMonkey/browsehandsfree#2]
## Overview
Continueing on from "[#1 Let's use an off the shelf proxy](https://github.com/TensorMonkey/browsehandsfree/issues/1)", let's use [PHP-Proxy](https://www.php-proxy.com/) to quickly set up a proxy on Heroku.

![image](https://user-images.githubusercontent.com/43509032/45986296-7ab4f980-c01f-11e8-8c5f-4957b69c803b.png)

## Tasks
- [x] Configure php-proxy
- [x] Create a nice landing page
- [x] Update the userbar on proxied pages
- [x] Upload to Heroku
- [x] Configure so that BrowseHandsfree.com points to it

**Comment by TensorMonkey** [comment]
So it took me a few years, but I finally understand Docker. Let's just build everything as a Docker image, which will allow us to easily switch between hosts when our trial runs out.

Our Docker will be responsible for the following:

![image](https://user-images.githubusercontent.com/43509032/45986296-7ab4f980-c01f-11e8-8c5f-4957b69c803b.png)

- User visit browsehandsfree.com on their device
- Enter a URL to visit
- Proxy makes HTTP request made on behalf of user
- Content is returned
- We inject our a11y scripts
- Render page

**Comment by TensorMonkey** [comment]
**Scope Change:** Let's use miniProxy, not php-proxy

**Comment by TensorMonkey** [comment]
Never mind on the Docker, it's like trying to build a car without understanding how a wheel works! We're only working with a simple PHP script so lets try and keep it simple

**Comment by TensorMonkey** [comment]
Complete!

![image](https://user-images.githubusercontent.com/43509032/46121585-39604d80-c1c9-11e8-965b-39cfacdfa452.png)
