### ISSUE TITLE
Setup Discourse on GAE

### ISSUE THREAD

**Issue by TensorMonkey** [TensorMonkey/browsehandsfree#9]
Let's setup [Discourse](https://www.discourse.org/), a forum, on GAE, making it accessible at https://browsehandsfree.com

- [ ] Install on GAE
- [ ] Create a "General" forum
- [ ] Create a "Bug" forum
- [ ] Create a "Feature Request" forum
- [ ] Create a "Startup" forum
